name: Nix Flake Build

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: published

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # Linux x86_64 builds
          - runs-on: ubuntu-latest
            package: re3
            system: x86_64-linux
          - runs-on: ubuntu-latest
            package: re3-vc
            system: x86_64-linux
          - runs-on: ubuntu-latest
            package: re3-lcs
            system: x86_64-linux
          # macOS x86_64 builds
          - runs-on: macos-13
            package: re3
            system: x86_64-darwin
          - runs-on: macos-13
            package: re3-vc
            system: x86_64-darwin
          - runs-on: macos-13
            package: re3-lcs
            system: x86_64-darwin
          # macOS ARM64 builds
          - runs-on: macos-latest
            package: re3
            system: aarch64-darwin
          - runs-on: macos-latest
            package: re3-vc
            system: aarch64-darwin
          - runs-on: macos-latest
            package: re3-lcs
            system: aarch64-darwin
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: re3
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: ${{ secrets.CACHIX_AUTH_TOKEN == '' }}
    
    - name: Build ${{ matrix.package }}
      run: |
        nix build ".#packages.${{ matrix.system }}.${{ matrix.package }}" -L
    
    - name: Check flake
      run: |
        nix flake check -L
    
    - name: Get binary name
      id: binary
      run: |
        case "${{ matrix.package }}" in
          re3)
            echo "name=re3" >> $GITHUB_OUTPUT
            ;;
          re3-vc)
            echo "name=reVC" >> $GITHUB_OUTPUT
            ;;
          re3-lcs)
            echo "name=reLCS" >> $GITHUB_OUTPUT
            ;;
        esac
    
    - name: Create release package
      run: |
        mkdir -p package
        cp result/bin/${{ steps.binary.outputs.name }} package/
        cp -r gamefiles/* package/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.package }}-${{ matrix.system }}
        path: package/
        if-no-files-found: error
