
name: reLCS cmake devkitA64 (Nintendo Switch)
on:
  pull_request:
  push:
    branches:
      - lcs
  release:
    types: published
jobs:
  build-nintendo-switch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Build files"
        run: |
          /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -S. -Bbuild -DRELCS_AUDIO=OAL -DLIBRW_PLATFORM=GL3 -DLIBRW_GL3_GFXLIB=GLFW -DRELCS_WITH_OPUS=False -DRELCS_VENDORED_LIBRW=True -DRELCS_INSTALL=True
          cmake --build build --parallel
      - name: "Create binary package (cpack)"
        working-directory: ./build
        run: |
          cpack
      - name: "Archive binary package (github artifacts)"
        uses: actions/upload-artifact@v4
        with:
          name: "switch-gl3"
          path: build/*.tar.xz
          if-no-files-found: error
