name: Nix Flake Build

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [re3]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: re3
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: ${{ secrets.CACHIX_AUTH_TOKEN == '' }}
    
    - name: Build ${{ matrix.package }}
      run: |
        nix build .#${{ matrix.package }} -L
    
    - name: Check flake
      run: |
        nix flake check -L
    
    - name: Get binary name
      id: binary
      run: |
        if [ "${{ matrix.package }}" == "re3" ]; then
          echo "name=re3" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.package }}" == "re3-vc" ]; then
          echo "name=reVC" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.package }}" == "re3-lcs" ]; then
          echo "name=reLCS" >> $GITHUB_OUTPUT
        fi
    
    - name: Create release package
      run: |
        mkdir -p package
        cp result/bin/${{ steps.binary.outputs.name }} package/
        cp -r gamefiles/* package/
        cd package
        zip -r ../${{ matrix.package }}-linux-x86_64.zip .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.package }}-linux-x86_64
        path: ${{ matrix.package }}-linux-x86_64.zip
        if-no-files-found: error
